/*
PURPOSE: TO CHECK MIN AND MAX DATE OF FACT_SALES_MONTHLY
ALSO TO CHECK WHETHE DATE IS MONTHLY OR DAILY
*/
SELECT
	MIN(date) AS MIN_DATE,
    MAX(date) AS MAX_DATE,
    COUNT(DISTINCT DATE) AS DISTINCT_DATE
FROM
	fact_sales_monthly
    

SELECT
	DISTINCT(DATE) AS DATES
FROM FACT_SALES_MONTHLY
LIMIT 10