/*
PURPOSE: TO CHECK THE GRAIN BASED ON SUSPECT PRODUCT_CODE, CUSTOMER_CODE, DATE

I WILL GROUP BY THE PRODUCT_CODE, CUSTOMER_CODE, DATE
i WILL CHECK THE REPEATED COUNT OF THE SAME PRODUCT_CODE+CUSTOMER_CODE+DATE
IF NO ROWS FOUND THAN IT IS THE GRAIN
OTHERWISE NEED TO TAKE OTHER STEP
*/

SELECT 
	`date`,
    PRODUCT_CODE,
    CUSTOMER_CODE,
    COUNT(*) AS ROW_COUNT
FROM fact_sales_monthly
GROUP BY
	`date`,
    PRODUCT_CODE,
    CUSTOMER_CODE
HAVING
	ROW_COUNT>1