/*
PURPOSE: TO VALIDATE THE VIEW BY COUNTING ROWS, MIN_DATE, MAX_DATE,
DISTINCT(FISCAL_YEAR), DISTINCT(DATE) ETC. WITH THE MAIN FACT_SALES_TABLE
*/

SELECT 
	COUNT(*) AS TOTAL_ROWS,
    MIN(DATE) AS MIN_DATE,
    MAX(DATE) AS MAX_DATE,
    COUNT(DISTINCT(DATE)) AS DIS_DATE,
    COUNT(DISTINCT(FISCAL_YEAR)) AS DIS_FY
FROM gdb041.vw_fact_sales_monthly_fy;